### ISSUE TITLE
The test result is empty

### ISSUE THREAD

**Issue by LiujiChen** [shehzaidi/pre-training-via-denoising#4]
Hi, thanks for the excellent work. I'm really interested and try to reproduce the experiments. I encounter the following error when test model. Ths result is empty, so I can not know the results for HOMO/LUMO on QM9. Did you encounter this problem in training?
![image](https://user-images.githubusercontent.com/83218347/216222690-3ec23c6b-575a-4afd-b0ef-b9a96f28e367.png)

**Comment by shehzaidi** [comment]
Hi! I would recommend using either Weights & Biases or the saved log files (in `log_dir`) to look at the full test results. Hope that helps!
