### ISSUE TITLE
Fail to reproduce the QM9 result

### ISSUE THREAD

**Issue by GentleZhu** [shehzaidi/pre-training-via-denoising#7]
Hi,

Thanks for the great work. While I try to reproduce the result on homo using checkpoint, I find the logged test_loss_y converges around 0.0158, which seems to differ a lot from 15.x meV. Can you help me understand this?

**Comment by shehzaidi** [comment]
Hi @GentleZhu, the units for the logged results are eV, rather than meV, so just multiply them by 1000, which should give you 15.8 meV.
