### ISSUE TITLE
Incomplete list of OutputModels?

### ISSUE THREAD

**Issue by a-r-j** [shehzaidi/pre-training-via-denoising#8]
Hiya,

I'm struggling to figure out what the config flag `output_model_noise: VectorOutput` maps to in the code? Has the `VectorOutput` model been renamed?

Thanks!!

**Comment by shehzaidi** [comment]
Hi @a-r-j, thanks for your question (and sorry for the late response)! Indeed, the config field `VectorOutput` maps to a module that's called `EquivariantVectorOutput`. This config parsing happens [here](https://github.com/shehzaidi/pre-training-via-denoising/blob/2d81667c4daf519a1bfd33f1e1257eefa527db61/torchmdnet/models/model.py#L89), and the module is defined [here](https://github.com/shehzaidi/pre-training-via-denoising/blob/2d81667c4daf519a1bfd33f1e1257eefa527db61/torchmdnet/models/output_modules.py#L157). Hope that helps!

**Comment by a-r-j** [comment]
Gotcha, thanks!!
